# Generated by Django 4.2.1 on 2023-07-09 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacion',
            name='numero_identificacion',
        ),
        migrations.RemoveField(
            model_name='donacion',
            name='tipo_donante',
        ),
        migrations.AddField(
            model_name='donacion',
            name='ciudad',
            field=models.CharField(default='Pasto', max_length=50),
        ),
        migrations.AddField(
            model_name='donacion',
            name='entidad',
            field=models.CharField(default='privada', max_length=100),
        ),
        migrations.AddField(
            model_name='donacion',
            name='identificacion',
            field=models.IntegerField(default=222222222, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(999999999999999)]),
        ),
        migrations.AddField(
            model_name='donacion',
            name='tipo_identificacion',
            field=models.CharField(default='Nit', max_length=100),
        ),
        migrations.AddField(
            model_name='donacion',
            name='tipo_regimen',
            field=models.CharField(default='régimen simple', max_length=50),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='fuente',
            field=models.CharField(default='propias', max_length=100),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='proposito',
            field=models.CharField(default='Sostenimiento', max_length=100),
        ),
    ]
