# Generated by Django 4.2.1 on 2023-07-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_remove_donacion_numero_identificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donacion',
            name='descripcion',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='donacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donacion',
            name='url_imagen',
            field=models.URLField(blank=True),
        ),
    ]
